spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sw-database.c70bhcy2r2jo.ap-northeast-2.rds.amazonaws.com:3306/MysqlDB?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: swproject
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true